Adding a ped preview
alberttheprince/rpemotes-reborn pull request #1
Opened 2024-07-06 19:07 UTC by enzo2991

![image](https://github.com/alberttheprince/rpemotes-reborn/assets/19875371/4632dd53-1ce5-4540-91ff-04962f9716ef)

https://youtu.be/DcgHAqxUv9Q

2024-07-06 19:14 UTC, alberttheprince requested changes
Just requesting the removal of Citizen. and would make reviewing changes a bit easier. No longer necessary to include it unless it's for [Citizen.Await] (https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/Citizen.Await) I believe.

2024-07-06 19:23 UTC, enzo2991 commented
yes, it's good when you want to make the thread wait for the Citizen.Wait or Await and I've just updated

2024-07-06 19:28 UTC, enzo2991 commented
They are the Same
Citizen.CreateThread is the original
CreateThread is the shorcut FiveM made for Citizen.CreateThread

2024-07-06 19:34 UTC, alberttheprince commented
> They are the Same Citizen.CreateThread is the original CreateThread is the shorcut FiveM made for Citizen.CreateThread

Since they function the same, we should leave it as it originally was when making the PR, without Citizen. as it's become common practice to use only Wait or CreateThread without the Citizen.

We can also remove things like:

--- RPEmotes by TayMcKenzieNZ, Mathu_lmn and MadsL, maintained by TayMcKenzieNZ ---
--- Download OFFICIAL version and updates ONLY at https://github.com/TayMcKenzieNZ/rpemotes ---
--- RPEmotes is FREE and ALWAYS will be. STOP PAYING SCAMMY FUCKERS FOR SOMEONE ELSE'S WORK!!! ---


As Tay is selling copies of rpemotes now and is no longer associated with RP emotes generally

2024-07-06 19:36 UTC, alberttheprince commented on client/EmoteMenu.lua
> -    infomenu:AddItem(NativeUI.CreateItem("Thanks ~o~DullPear 🍐~s~", "~o~DullPear~s~ for the original dpemotes ❤️"))
Try to cherry pick the code you made for the animation menu.

2024-07-07 07:38 UTC, alberttheprince commented
I've made several changes and corrections to maintain the original functionality, style, and deleted things like the comments. Would appreciate if you could give this a test run to see if it's OK.

2024-07-07 11:53 UTC, enzo2991 commented
It's ok now, I just corrected the config, the title color and outline were missing.

2024-07-07 22:56 UTC, TayMcKenzieNZ commented
> As Tay is selling copies of rpemotes now and is no longer associated with RP emotes generally

Please stop name dropping me. I *am* still maintaining *my* project and am within my right to sell *my* work. You are the only person on earth who has a problem with it yet, you are the very reason *why* it's being sold.

2024-07-08 01:39 UTC, TayMcKenzieNZ commented
Why are you openly name dropping me but yet delete my comments? If you have something to say, say it. My DMs are open, Noor, although I'm confused as to why you keep poking the wasp nest. It's very, very immature of you.

2024-07-08 02:13 UTC, merged

2024-07-08 04:11 UTC, TayMcKenzieNZ commented
Repository owner deleted a comment from TayMcKenzieNZ 1 hour ago